apiVersion: v1
kind: Service
metadata:
  name: streaming-app
  namespace: streaming
  labels:
    app: streaming-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30086
    protocol: TCP
    name: http
  selector:
    app: streaming-app

